### ISSUE TITLE
Doesn't supports course titles with apostrophes.

### ISSUE THREAD

**Issue by Muddr** [solmsted/super-mario-maker-client#1]
Fetching course data that has apostrophes in the title are returned incorrectly.

Sample Code: `DCBA-0000-00E9-C9E0`

Expected Title: `tehSHELL'S Adventure`
Returned Title: `S Adventure`

Not sure if any other data also has this issue.

**Comment by solmsted** [comment]
Thanks for reporting!  The 0.1.0 release should resolve this issue.  I'm still working on adding better unit tests but I went ahead and added a test for a course with an apostrophe in its title to make sure this issue stays fixed.
